email: 
password: 

disableAntiLock: False

remote: True

experienceLevel:
 internship: True
 entry: True
 associate: False
 mid-senior level: False
 director: False
 executive: False
 
jobTypes:
 full-time: False
 contract: True
 part-time: True
 temporary: True
 internship: True
 other: False
 volunteer: False
 
date:
 all time: False
 month: True
 week: False
 24 hours: False
 
positions:
 - python
 - programming
 - game
 - data
 - tech
 - analysis
 - business
 - AI
 #- ...

locations:
 - Manchester
 - England
 #- A third location
 #- ...
distance: 25

outputFileDirectory: C:\Users\myDirectory\

companyBlacklist:
 #- company
 #- company2

titleBlacklist:
 - founder
 #- word2

uploads:
 resume: C:\Users\golan\OneDrive\Documents\Company Specific CV\Saad Golandaz - Tech.pdf
 # Cover letter is optional
 #coverLetter: C:\Users\myDirectory\CoverLettter.pdf


# ------------ QA section -------------------

# ------------ Additional parameters: checkboxes ---------------
checkboxes:
 # Do you have a valid driver's license? (yes/no checkbox)
 driversLicence: True
 # Will you now, or in the future, require sponsorship for employment visa status (e.g. H-1B visa status)? (yes/no checkbox)
 # This is relative to the location and your citizenship applying above, and same with legallyAuthorized.
 requireVisa: False
 # Are you legally authorized to work in COUNTRY? (yes/no checkbox)
 legallyAuthorized: True
 # We must fill this position urgently. Can you start immediately? (yes/no checkbox)
 urgentFill: True
 # Are you comfortable commuting to this job's location? (yes/no checkbox)
 commute: True
 # Have you completed the following level of education: DEGREE TYPE? (yes/no checkbox)
 degreeCompleted:
  - High School Diploma
  - Bachelor's Degree
  # - Associate's Degree
  # - Master's Degree
  # - Master of Business Administration
  # - Doctor of Philosophy
  # - Doctor of Medicine
  # - Doctor of Law
 # Are you willing to undergo a background check, in accordance with local law/regulations?
 backgroundCheck: True

# ------------ Additional parameters: univeristyGpa ---------------
universityGpa: 4.0

# ------------ Additional parameters: languages ---------------
languages:
 english: Native or bilingual # None, Conversational, Professional, Native or bilingual


# ------------ Additional parameters: years of INDUSTRY experience ---------------
# How many years of TECHNOLOGY experience do you currently have? (whole numbers only)
experience:
 # normal ones
 Accounting/Auditing: 3
 Administrative : 2
 Advertising : 1
 Analyst : 2
 Art/Creative: 1
 Business Development: 5
 Consulting: 3
 Customer Service: 2
 Distribution Design: 0
 Education: 5
 Engineering: 2
 Finance: 2
 General Business: 2
 Health Care Provider: 0
 Human Resources: 4
 Information Technology: 2
 Legal: 0
 Management: 0
 Manufacturing: 6
 Marketing: 1
 Public Relations: 4
 Purchasing: 4
 Product Management: 3
 Project Management: 5
 Production: 4
 Quality Assurance: 3
 Research: 5
 Sales: 2
 Science: 3
 Strategy/Planning: 3
 Supply Chain: 2
 Training: 5
 Writing/Editing: 3
 # end normal ones
 # put your custom ones here
 #C++: 0
 Python: 4
 # default to put for any skill that you did not list
 default: 1
 # end custom ones


# ------------ Additional parameters: years of technology experience ---------------
# How many years of work experience do you have using TECHNOLOGY? (whole numbers only)
technology:
 python: 4
 selenium: 2
 # default to put for any skill that you did not list
 default: 1
# ------------ Additional parameters: personal info ---------------
personalInfo:
 First Name: Saad
 Last Name: Golandaz
 Phone Country Code: United Kingdom (+44) # See linkedin for your country code, must be exact
 Mobile Phone Number: 07915897908
 Street address: 61A, Brantingham Road
 City: Manchester # Include the state/province as well!
 State: Greater Manchester
 Zip: M168PA
 Linkedin: https://www.linkedin.com/in/saadgolandaz/
 Website: https://www.my-website.com # github/website is interchangable here

# ------------ Additional parameters: USA employment crap ---------------
eeo:
 gender: Male
 race: Asian
 vetran: None
 disability: None
 citizenship: Indian